Lengthen fields so we can use more characters
The deployed version of the app is failing when loading data

```
django.db.utils.DataError: value too long for type character varying(25)
```

We've got short titles that are at least 30 chars, so I'm just gonna make them long as funk so we don't have to think about this again.